# Generated by Django 2.2.10 on 2020-03-01 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0002_scholarship'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='scholarship',
            new_name='ScholarshipDetails',
        ),
    ]
