# Generated by Django 2.2.10 on 2020-03-01 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0003_auto_20200301_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshipdetails',
            name='category',
            field=models.CharField(default=1, max_length=2000),
            preserve_default=False,
        ),
    ]
