# Generated by Django 2.2.10 on 2020-03-04 17:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0004_scholarshipdetails_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshipdetails',
            name='reward',
            field=models.CharField(default=django.utils.timezone.now, max_length=2000),
            preserve_default=False,
        ),
    ]
