# Generated by Django 2.2.10 on 2020-03-08 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0008_auto_20200304_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarshipdetails',
            name='income',
            field=models.CharField(max_length=200),
        ),
    ]
