# Generated by Django 2.2.10 on 2020-03-08 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0009_auto_20200308_1107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scholarshipdetails',
            old_name='date',
            new_name='end_date',
        ),
    ]
