# Generated by Django 2.2.10 on 2020-03-08 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0010_auto_20200308_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshipdetails',
            name='updated_end_date',
            field=models.DateField(null=True),
        ),
    ]
