# Generated by Django 2.2.10 on 2020-03-09 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0011_scholarshipdetails_updated_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshipdetails',
            name='updated_link',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
