# Generated by Django 2.2.10 on 2020-03-11 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0016_agree_info_educational_info_personal_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_info',
            name='address',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='personal_info',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='personal_info',
            name='first_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='personal_info',
            name='gender',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='personal_info',
            name='last_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
