# Generated by Django 2.2.10 on 2020-03-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0017_auto_20200312_0010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applied_Schlarships',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('dob', models.DateField(null=True)),
                ('address', models.TextField(max_length=2000, null=True)),
                ('phone', models.IntegerField(max_length=9999999999)),
                ('enrolment', models.IntegerField(max_length=200000000000)),
                ('ssc_marks', models.IntegerField()),
                ('hsc_marks', models.IntegerField()),
                ('college_name', models.CharField(max_length=500)),
                ('board', models.CharField(max_length=200)),
                ('semester', models.IntegerField()),
                ('department', models.CharField(max_length=200)),
                ('income_certificate', models.ImageField(upload_to='assets/images/income_images')),
                ('caste_certificate', models.ImageField(upload_to='assets/images/caste_certificate')),
                ('passport_photo', models.ImageField(upload_to='assets/images/passport_photo')),
                ('status', models.CharField(max_length=200)),
            ],
        ),
    ]
