# Generated by Django 2.2.10 on 2020-03-13 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0019_applied_schlarships_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='applied_schlarships',
            name='scholarship_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
