# Generated by Django 2.2.10 on 2020-03-13 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0021_auto_20200313_1012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_scholarship',
            old_name='name',
            new_name='student',
        ),
        migrations.AddField(
            model_name='student_scholarship',
            name='scholarship',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='scholarship.ScholarshipDetails'),
            preserve_default=False,
        ),
    ]
