# Generated by Django 2.2.10 on 2020-03-15 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0023_scholarshipdetails_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarshipdetails',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
