# Generated by Django 2.2.10 on 2020-03-15 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0024_auto_20200315_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshipdetails',
            name='gender',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
