# Generated by Django 2.2.10 on 2020-03-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0025_scholarshipdetails_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agree_info',
            name='agree',
            field=models.BooleanField(),
        ),
    ]
