# Generated by Django 2.2.10 on 2020-03-17 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0026_auto_20200316_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_info',
            name='family_income',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
