# Generated by Django 2.2.10 on 2020-03-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0029_personal_info_highest_qualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educational_info',
            name='hsc_board',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='educational_info',
            name='hsc_marks',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='educational_info',
            name='hsc_percentage',
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
