# Generated by Django 2.2.10 on 2020-03-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0030_auto_20200317_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applied_scholarships',
            name='passport_photo',
            field=models.ImageField(upload_to='certificate'),
        ),
    ]
