# Generated by Django 2.2.10 on 2020-03-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0031_auto_20200318_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applied_scholarships',
            name='caste_certificate',
            field=models.ImageField(upload_to='certificate'),
        ),
        migrations.AlterField(
            model_name='applied_scholarships',
            name='income_certificate',
            field=models.ImageField(upload_to='certificate'),
        ),
    ]
