# Generated by Django 2.2.10 on 2020-04-01 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0035_auto_20200331_1610'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student_Scholarship',
        ),
    ]
