# Generated by Django 2.2.10 on 2020-04-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0037_auto_20200401_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applied_scholarships',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
